// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wm.bs.domain;

import com.wm.bs.domain.Wm_log;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Wm_log_Roo_Configurable {
    
    declare @type: Wm_log: @Configurable;
    
}
